snowflake_demo:
  outputs:
   prod:
    account: "{{ env_var('DBT_ACCOUNT') }}"
    database: tonight
    password: "{{ env_var('DBT_PASSWORD') }}"
    role: ACCOUNTADMIN
    schema: my_schema
    threads: 1
    type: snowflake
    user: "{{ env_var('DBT_USER') }}"
    warehouse: COMPUTE_WH
  target: prod

